###############################################################################
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html
###############################################################################

# Book settings
title: GeoClaw Tsunami Tutorial  # The title of the book. Will be placed in the left navbar.
author: R.J. LeVeque  # The author of the book
copyright: "2025"  # Copyright year to be placed in the footer
logo: images/GeoClawLogoTitle.jpg

# Force re-execution of notebooks on each build, or cache results:
# See https://jupyterbook.org/content/execute.html
# https://jupyterbook.org/en/stable/content/execute.html#execute-cache
execute:
  execute_notebooks: cache

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: GeoClawTsunamiTutorial.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/rjleveque/geoclaw_tsunami_tutorial
  path_to_book: ""
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: images/geoclaw-favicon-32x32.png
  use_issues_button: true
  use_repository_button: true

# See  https://jupyterbook.org/en/stable/advanced/html.html#manually-specify-extra-files-folders-to-be-included-in-a-website
sphinx:
  config:
    html_extra_path: ['_extra_html']
    # e.g _extra_html/GTT/dtopo/abc.html is copied to GTT/dtopo/
  extra_extensions:
    - sphinx_iframes

parse:
  myst_enable_extensions: 
    # https://myst-parser.readthedocs.io/en/latest/syntax/optional.html
    - amsmath
    - colon_fence
    #- deflist
    - dollarmath
    #- html_admonition
    #- html_image
    - linkify
    - replacements
    #- smartquotes
    - substitution
    - strikethrough
  myst_url_schemes: ["mailto", "http", "https", "wiki", "doi"] 
  myst_dmath_double_inline: true  # Allow display math ($$) inline
  myst_substitutions:
    WEBSITE : "https://rjleveque.github.io/geoclaw_tsunami_tutorial/"
    CLAWDOCS : "https://www.clawpack.org"

